### ISSUE TITLE
[headless mode]: permission issue in `register_theme` upon import

### ISSUE THREAD

**Issue by jluethi** [haesleinhuepf/napari-segment-blobs-and-things-with-membranes#20]
Hey Robert,

[This issue may actually belong to a different package, but I couldn't trace it back and it triggers for us when using nsbatwm. It does not trigger when we use e.g. napari-skimage-regionprops as part of a napari workflow]

We're using nsbatwm as part of the Fractal workflows on a slurm cluster. As part of this setup, the python environments are owned by a service user, but used by the actual users running some jobs. The way we set it up, users can read the python environment, but they don't have write access to it.

That can become an issue when napari needs to use cache files it would normally put in e.g. a hidden folder in the python virtualenv directory. We can mostly work around this by setting things like `NAPARI_CONFIG=${HOME}/.cache/NAPARI_CACHE_DIR` for each user (=> napari would use that cache for some things, not something in the virtual environment).

This had worked last summer, but stopped working now for the nsbatwm plugin. It's not a version question of nsbatwm, as it fails with version 0.3.3 and 0.3.4. We rarely use nsbatwm in our napari workflows at the moment, so I haven't manage to trace back the time it stopped working yet.

Some theme imports appear to get triggered and they aren't collected from the `$NAPARI_CONFIG` folder, but instead in the home folder of the user that created the virtual environment (e.g. `/data/homes/fractal/.cache/napari/`). Our users don't have access there, thus importing a workflow with nsbatwm now fails.

<details>

<summary>Here's the full traceback:</summary>

```
Traceback (most recent call last):
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/fractal_tasks_core/napari_workflows_wrapper.py", line 604, in <module>
    run_fractal_task(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/fractal_tasks_core/_utils.py", line 104, in run_fractal_task
    metadata_update = task_function(**task_args.dict())
  File "/net/nfs4/pelkmanslab-fileserver-common/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/fractal_tasks_core/napari_workflows_wrapper.py", line 115, in napari_workflows_wrapper
    wf: napari_workflows.Worfklow = load_workflow(workflow_file)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari_workflows/_io_yaml_v1.py", line 36, in load_workflow
    return unsafe_load(stream)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/__init__.py", line 145, in unsafe_load
    return load(stream, UnsafeLoader)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 523, in construct_python_tuple
    return tuple(self.construct_sequence(node))
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 102, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 570, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 719, in find_python_name
    return super(UnsafeConstructor, self).find_python_name(name, mark, unsafe=True)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/yaml/constructor.py", line 551, in find_python_name
    __import__(module_name)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari_segment_blobs_and_things_with_membranes/__init__.py", line 23, in <module>
    from napari_time_slicer import time_slicer
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari_time_slicer/__init__.py", line 4, in <module>
    from ._function import napari_experimental_provide_function
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari_time_slicer/_function.py", line 7, in <module>
    from napari.layers import Image, Labels, Layer
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/layers/base/base.py", line 28, in <module>
    from ...utils.key_bindings import KeymapProvider
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/utils/key_bindings.py", line 46, in <module>
    from ..settings import get_settings
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/settings/__init__.py", line 5, in <module>
    from ._base import _NOT_SET
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/settings/_base.py", line 18, in <module>
    from ._yaml import PydanticYamlMixin
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/settings/_yaml.py", line 9, in <module>
    from ._fields import Version
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/settings/_fields.py", line 6, in <module>
    from ..utils.theme import available_themes
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/utils/theme.py", line 320, in <module>
    register_theme('dark', DARK)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/utils/theme.py", line 252, in register_theme
    build_theme_svgs(name)
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/resources/_icons.py", line 163, in build_theme_svgs
    write_colorized_svgs(
  File "/data/homes/fractal/joel/fractal_v1/fractal-demos/examples/server/FRACTAL_TASKS_DIR/.fractal/fractal-tasks-core0.7.2/venv/lib/python3.8/site-packages/napari/resources/_icons.py", line 145, in write_colorized_svgs
    dest.mkdir(parents=True, exist_ok=True)
  File "/data/homes/fractal/.conda/envs/fractal-server-1.0.7/lib/python3.8/pathlib.py", line 1297, in mkdir
    if not exist_ok or not self.is_dir():
  File "/data/homes/fractal/.conda/envs/fractal-server-1.0.7/lib/python3.8/pathlib.py", line 1422, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/data/homes/fractal/.conda/envs/fractal-server-1.0.7/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/data/homes/fractal/.cache/napari/0.4.17/_themes/dark'
```

</details>

------

Do you know whether the way this cache folder for the theme gets picked is something set by nsbatwm (unlikely, given that it worked with version 0.3.3 before and now breaks), something in the napari workflows import mode of nsbatwm or by core napari? Are you maybe aware of an environment variable that can be set to determine which cache folder is used to store themes? If we can set it similar to the `NAPARI_CONFIG` variable, we can avoid this issue.
I looked around a bit in the napari code, but the place where NAPARI_CONFIG comes up (e.g. [here](https://github.com/napari/napari/blob/ee94c35c04674ddc8e89ed63ac7674c27fa8fc6c/napari/settings/_napari_settings.py), no other path configs are set.

I suspect there is a combination of the main napari version and the versions of napari workflows and its dependencies that would make this work again. But would be great to get this working again in the current release version :)

The relevant versions of packages are:
```
napari==0.4.17
napari-assistant==0.4.4
napari-console==0.0.7
napari-plugin-engine==0.2.0
napari-segment-blobs-and-things-with-membranes==0.3.3
napari-skimage-regionprops==0.8.1
napari-svg==0.1.6
napari-time-slicer==0.4.9
napari-tools-menu==0.1.19
napari-workflows==0.2.8
```

Also tested with napari-segment-blobs-and-things-with-membranes==0.3.4, same issue there.
As mentioned above, it's not a general things with using napari workflows. We use napari-skimage-regionprops quite heavily in some workflows and have not had this issue with it.

**Comment by jluethi** [comment]
Ok, it took a bit of digging, but I figured out a way to work around this:
Setting the environment variable `XDG_CACHE_HOME` to something that the user will have write access and the `NAPARI_CONFIG` variable to a path to a json file the user can write to (doesn't need to exist before running things) does the trick for me.


Context:
This plugin and some other plugins (we just started testing apoc for the same purpose) import the napari_time_slicer plugin (even if no time slicing is done in the workflow). The napari_time_slicer plugin imports some napari classes during its import. The import that can be somewhat tricky was `from napari.layers import Image, Labels, Layer`.

Something must have changed on the napari side late last year, because that wasn't an issue before. But with the current versions, they use appdirs to infer the location for all those .cache directories and this automatic detection does not work in our somewhat custom setup where a service user creates environments and runs a server, but then individual users submit workflows.
Luckily, setting the `XDG_CACHE_HOME` & `NAPARI_CONFIG` variables to something fitting then does the trick :)
