### ISSUE TITLE
importlib.find_loader is deprecated

### ISSUE THREAD

**Issue by longyuxi** [haesleinhuepf/napari-segment-blobs-and-things-with-membranes#36]
Hello,

`importlib.find_loader` is deprecated and removed in Python 3.12.6. This leads to an error when I manually draw clusters in `Tools -> Visualizations -> Plot measurements (ncp)`:

```
Traceback (most recent call last):
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/matplotlib/widgets.py", line 2271, in release
    self._release(event)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/matplotlib/widgets.py", line 3712, in _release
    self.onselect(self.verts)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_Qt_code.py", line 268, in onselect
    self.parent.manual_clustering_method(self.ind_mask)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_plotter.py", line 72, in manual_clustering_method
    self.run(
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_plotter.py", line 396, in run
    cluster_image = generate_cluster_image(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_utilities.py", line 135, in generate_cluster_image
    return relabel(label_image, list(predictionlist_new)).astype("uint64")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_skimage_regionprops/_parametric_images.py", line 166, in relabel
    loader = importlib.find_loader("pyclesperanto_prototype")
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'find_loader'
Traceback (most recent call last):
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/matplotlib/widgets.py", line 2271, in release
    self._release(event)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/matplotlib/widgets.py", line 3712, in _release
    self.onselect(self.verts)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_Qt_code.py", line 268, in onselect
    self.parent.manual_clustering_method(self.ind_mask)
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_plotter.py", line 72, in manual_clustering_method
    self.run(
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_plotter.py", line 396, in run
    cluster_image = generate_cluster_image(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_clusters_plotter/_utilities.py", line 135, in generate_cluster_image
    return relabel(label_image, list(predictionlist_new)).astype("uint64")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yul4024/miniforge3/envs/napari/lib/python3.12/site-packages/napari_skimage_regionprops/_parametric_images.py", line 166, in relabel
    loader = importlib.find_loader("pyclesperanto_prototype")
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'find_loader'

```

**Comment by longyuxi** [comment]
Sorry, I just realized that the install instructions specified specifically Python=3.9 and Napari=0.4.19.

**Comment by haesleinhuepf** [comment]
Hi @longyuxi ,

thanks for the feedback! I think the bug report would be better in https://github.com/BiAPoL/napari-clusters-plotter 

Thanks!

Best,
Robert

**Comment by longyuxi** [comment]
Hi @haesleinhuepf ,

Thank you so much! This repository is great work.

Yuxi
